# Generated by Django 6.0.2 on 2026-05-05 12:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='accounts.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('voter_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('officer', 'Election Officer'), ('voter', 'Voter')], default='voter', max_length=10)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set_v2', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set_v2', to='auth.permission')),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.assembly')),
                ('booth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.booth')),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.constituency')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='accounts.assembly')),
            ],
        ),
        migrations.AddField(
            model_name='booth',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='accounts.village'),
        ),
        migrations.AddField(
            model_name='user',
            name='village_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.village'),
        ),
        migrations.CreateModel(
            name='VillageAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=30, unique=True, verbose_name='Admin ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('full_name', models.CharField(max_length=150)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('nation', models.CharField(default='India', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False, help_text='Becomes True once the admin completes online registration.')),
                ('designated_role', models.CharField(choices=[('admin', 'Admin'), ('officer', 'Election Officer')], default='admin', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'village_admins',
                'indexes': [models.Index(fields=['admin_id'], name='village_adm_admin_i_ef0a55_idx'), models.Index(fields=['email'], name='village_adm_email_0a57f7_idx'), models.Index(fields=['village', 'state'], name='village_adm_village_11747b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoterRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('full_name', models.CharField(max_length=150)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('nation', models.CharField(default='India', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False, help_text='Becomes True once the voter completes online registration.')),
                ('designated_role', models.CharField(choices=[('admin', 'Admin'), ('officer', 'Election Officer'), ('voter', 'Voter')], default='voter', help_text='If set to Admin, the user automatically becomes the Village Admin upon registration.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voter_rolls',
                'indexes': [models.Index(fields=['voter_id'], name='voter_rolls_voter_i_02b19f_idx'), models.Index(fields=['email'], name='voter_rolls_email_f48744_idx'), models.Index(fields=['village', 'state'], name='voter_rolls_village_67b7bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoterVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_voter_id', models.CharField(blank=True, max_length=30)),
                ('aadhaar_last4', models.CharField(blank=True, help_text='Last 4 digits only', max_length=4)),
                ('full_name_on_card', models.CharField(blank=True, max_length=150)),
                ('dob_on_card', models.DateField(blank=True, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='voter_cards/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voter_verifications',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['state', 'district', 'village'], name='users_state_1056c7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['voter_id'], name='users_voter_i_c1d34a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
    ]
