# Generated by Django 6.0.2 on 2026-05-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('full_name', models.CharField(max_length=150)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('nation', models.CharField(default='India', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False, help_text='Becomes True once the voter completes online registration.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voter_rolls',
                'indexes': [models.Index(fields=['voter_id'], name='voter_rolls_voter_i_02b19f_idx'), models.Index(fields=['email'], name='voter_rolls_email_f48744_idx'), models.Index(fields=['village', 'state'], name='voter_rolls_village_67b7bd_idx')],
            },
        ),
    ]
