# Generated by Django 6.0.2 on 2026-05-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_voter_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterroll',
            name='designated_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('officer', 'Election Officer'), ('voter', 'Voter')], default='voter', help_text='If set to Admin, the user automatically becomes the Village Admin upon registration.', max_length=10),
        ),
    ]
