# Generated by Django 6.0.2 on 2026-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_voterroll_designated_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('full_name', models.CharField(max_length=150)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('nation', models.CharField(default='India', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False, help_text='Becomes True once the admin completes online registration.')),
                ('designated_role', models.CharField(choices=[('admin', 'Admin'), ('officer', 'Election Officer')], default='admin', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'village_admins',
                'indexes': [models.Index(fields=['admin_id'], name='village_adm_voter_i_e6201c_idx'), models.Index(fields=['email'], name='village_adm_email_0a57f7_idx'), models.Index(fields=['village', 'state'], name='village_adm_village_11747b_idx')],
            },
        ),
    ]
