# Generated by Django 6.0.2 on 2026-05-05 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='parties/')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('national', 'National'), ('state', 'State'), ('village', 'Village')], default='village', max_length=20)),
                ('constituency', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'elections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='candidates/symbols/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('party_photo', models.ImageField(blank=True, null=True, upload_to='candidates/party_photos/')),
                ('party_brochure', models.FileField(blank=True, null=True, upload_to='candidates/brochures/')),
                ('manifesto', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.party')),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['status'], name='elections_status_eb3191_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['level'], name='elections_level_7631dc_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['state', 'district', 'village'], name='elections_state_e10114_idx'),
        ),
    ]
