# Generated by Django 6.0.2 on 2026-05-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party_photo',
            field=models.ImageField(blank=True, null=True, upload_to='parties/'),
        ),
    ]
