# Generated by Django 6.0.2 on 2026-05-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_candidate_party_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party_brochure',
            field=models.ImageField(blank=True, null=True, upload_to='brochures/'),
        ),
    ]
