# Generated by Django 4.2.30 on 2026-05-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_per_election',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='booth',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_hash',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election'),
        ),
    ]
